# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "github-pages", group: :jekyll_plugins

gem "jekyll", "~> 3.9.5"

gem "jekyll-relative-links", "~> 0.7.0"

gem "jekyll-remote-theme", "~> 0.4.3"
