name: Pages deploy
on: [push]
jobs:
    build_docs:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository 
              uses: actions/checkout@v4
            - run: echo "Step 1 complete"
            - name: install ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.4'
                bundler-cache: true
            - name: bundle install
              run: bundle install
              working-directory: ./docs
            - name: build site
              run: bundle exec jekyll build
              working-directory: ./docs
            - name: upload site
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./docs/_site